[package]
name = "asphalt_calculator"
version = "1.0.0"
description = "Petroleum and Asphalt Calculator (ASTM D1250 / D4311)"
authors = ["litao"]
edition = "2021"

[lib]
name = "asphalt_calculator_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# ⬇️ 下面是新添加的 ⬇️
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true